### ISSUE TITLE
arcpullr errors

### ISSUE THREAD

**Issue by dcarver1** [GeospatialCentroid/Colorado-EnviroScreen#18]
Both these links are potential climate related indicators 

not having any luck with pulling from rest service with arcpullr. 

need to evaluate 

dought 
https://geodata.epa.gov/arcgis/rest/services/OAR_OAP/Drought/MapServer

floodplains
https://enviroatlas.epa.gov/arcgis/rest/services/Supplemental/Estimated_floodplain_CONUS_WM/ImageServer

**Comment by ccmothes** [comment]
Okay I got this to work:

Since drought is a map service and floodplains is an image service, they need to use different functions in arcpullr, which both require an sf object to set the bounding box for the api call. For this I used the colorado shapefile which needed to be transformed to wgs 84.

`co <- st_read("data/state/colorado.geojson") %>% st_transform(4326)`

`drought <- arcpullr::get_map_layer("https://geodata.epa.gov/arcgis/rest/services/OAR_OAP/Drought/MapServer", co)`

`flood <- arcpullr::get_image_layer("https://enviroatlas.epa.gov/arcgis/rest/services/Supplemental/Estimated_floodplain_CONUS_WM/ImageServer", co)`

However these functions read them in as rasters

**Comment by dcarver1** [comment]
Thanks for getting at this Caitlin. The datasets a not available at a resolution to be useful for this study. 
Reference this issue in the future if other arcpullr errors are observed .
